### ISSUE TITLE
File Creator: Saving issue

### ISSUE THREAD

**Issue by dfessor** [chrisiweb/Parhamer_connection#4]
Can't save, when folder doesn't exist
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "Aufgabensammlung (inoffiziell)/LaTeX File Creator 1.2.py", line 351, in save_file_typ1
    for all in os.listdir(gk_path_temp):
FileNotFoundError: [Errno 2] No such file or directory: 'Typ 1 Aufgaben/_Grundkompetenzen/AG - Algebra und Geometrie/AG-L 5.3/Einzelbeispiele'
```

**Comment by chrisiweb** [comment]
not sure if this is still an issue? @dfessor

**Comment by dfessor** [comment]
@chrisiweb In order for the LaMA.py to work it needs:
- `./_database/_config/config1.yml`
- `./_database/_config/update/__version__.txt`

After that the script starts. It can't find anything, but doesn't crash by looking for/in directories, that don't exist.

To make a new math-problem i tried to make the file structure, e.g.
`./_database/Typ1Aufgaben/_Grundkompetenzen/AG/AG-L 3.6/Einzelbeispiele` (mind the **space** in `AG-L 3.6`, we should change that at times...)

But the program said: "Der Ordner "Beispieleinreichung" konnte nicht gefunden werden und muss zuerst für Sie freigegeben werde.
Derzeit können keine neuen Aufgaben eingegeben werden.
This is bad.

**Comment by dfessor** [comment]
- #35 should solve directory issues
- spaces in dirnames is still a light issue
- If beispielrechnung is not found it would be good to have a temporary dir, that is synced as soon as it is allowed to do so.
