### ISSUE TITLE
failed texmaker translation and pdf-build due to `substitutefont.sty` missing in new releases of tex (2024)

### ISSUE THREAD

**Issue by netlimpopo** [chrisiweb/Parhamer_connection#48]
## Problem 
Since August 2023 LaTex package ```substitutefont.sty``` is deprecated, therefore Lama builds fail with 2024 Version of LaTex. 
Even the "Startdocument.tex" provided by lama fails to be built.
Only recently have I deleted the old 2023 texlive and and I have been encounting this problem since. Building other .tex documents work though. 
Also the Lama preview fails to build as a consequence. 

## Possible Solution/Workaround
\DeclareFontFamilySubstitution could be used instead. 

\newfontfamily in Unicode laTex does not fail. 

## Error messages
"! LaTeX Error: File `substitutefont.sty' not found.Type X to quit or <RETURN> to proceed,or enter new name. (Default extension: sty)Enter file name:! Emergency stop.<read > \substitutefont"

<details><summary>error message</summary>
Texmaker error code:
```
! LaTeX Error: File `substitutefont.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
Enter file name:
! Emergency stop.
<read *>
l.50 \substitutefont
{LPH}{\familydefault}{cmr}^^M
*** (cannot \read from terminal in nonstop modes)
Here is how much of TeX's memory you used:
37044 strings out of 474050
886244 string characters out of 5746304
1926751 words of memory out of 5000000
58822 multiletter control sequences out of 15000+600000
561366 words of font info for 38 fonts, out of 8000000 for 9000
1141 hyphenation exceptions out of 8191
133i,0n,136p,738b,609s stack positions out of 10000i,1000n,20000p,200000b,200000s
No pages of output.
```
</details>

**Comment by chrisiweb** [comment]
The error should now be resolved after updating the necessary srdp-mathematik.sty.
